# Set the desired connector
# a list of:
# name/tag, type of database, hostname, port, database
providers:
   - name: marketplace_rs
     db: "mongodb://localhost:27017/recommender_dev"
   - name: content-based engine
     db: "mongodb://localhost:27017/athena_dev"
   - name: online_engine
     db: ""

# The database where the Preprocessor's
# and RSmetrics data are stored
datastore: "mongodb://localhost:27017/rsmetrics"

service:
    # Use the EOSC-Marketplace webpage
    # to retrieve resources and associate the page_id and the service_id
    store: './page_map' # or null
    service_list_url: 'https://search.marketplace.eosc-portal.eu/api/web/search-results'
    # if true it keeps only published, otherwise all
    # this has an effect in exporting when from is set to 'source' 
    # and also in metrics calculations where service is considered
    published: true
    category:
       content-based engine: [service]
       marketplace_rs: [service]
       online_engine: [training, data_source]
